Day 1: Vectors, Vector Spaces, and Inner Product Spaces
Let me start with the core concepts and then give you today's practical problems.
Key Concepts:
* Vectors: Objects that have magnitude and direction, represented as arrays of numbers
* Vector Spaces: Collections of vectors that can be added together and multiplied by scalars
* Inner Product: A way to multiply vectors that gives a scalar (like dot product)
* Norm: The "length" of a vector, often calculated as √(v·v)
Today's Problems:
Finance Problem: You're analyzing a portfolio with 4 assets. The daily returns over 5 days are represented as vectors:
* Asset A: [0.02, -0.01, 0.03, 0.01, -0.02]
* Asset B: [0.01, 0.02, -0.01, 0.02, 0.01]
Calculate the correlation coefficient between these two assets using vector operations (hint: use inner products and norms).
AI/ML Problem: In a recommendation system, user preferences are represented as vectors. User 1 likes genres with weights [4, 2, 1, 3] for [Action, Comedy, Drama, Sci-Fi], and User 2 has weights [3, 3, 2, 4]. Calculate the cosine similarity between these users to determine how similar their tastes are.
Methods to use:
* Inner product (dot product): a·b = Σ(aᵢbᵢ)
* Vector norm: ||v|| = √(v·v)
* Correlation coefficient: r = (a·b)/(||a|| × ||b||) after centering the data
* Cosine similarity: cos(θ) = (a·b)/(||a|| × ||b||)
Try these problems and when you're ready, type "solve" and I'll walk you through the step-by-step solutions!

Finance Problem Solution: Portfolio Correlation
Step 1: Set up the data
* Asset A returns: [0.02, -0.01, 0.03, 0.01, -0.02]
* Asset B returns: [0.01, 0.02, -0.01, 0.02, 0.01]
Step 2: Calculate means
* Mean of A: μₐ = (0.02 + (-0.01) + 0.03 + 0.01 + (-0.02))/5 = 0.03/5 = 0.006
* Mean of B: μᵦ = (0.01 + 0.02 + (-0.01) + 0.02 + 0.01)/5 = 0.05/5 = 0.01
Step 3: Center the data (subtract means)
* A_centered = [0.02-0.006, -0.01-0.006, 0.03-0.006, 0.01-0.006, -0.02-0.006]
* A_centered = [0.014, -0.016, 0.024, 0.004, -0.026]
* B_centered = [0.01-0.01, 0.02-0.01, -0.01-0.01, 0.02-0.01, 0.01-0.01]
* B_centered = [0, 0.01, -0.02, 0.01, 0]
Step 4: Calculate inner product A_centered · B_centered = (0.014×0) + (-0.016×0.01) + (0.024×-0.02) + (0.004×0.01) + (-0.026×0) = 0 + (-0.00016) + (-0.00048) + 0.00004 + 0 = -0.0006
Step 5: Calculate norms
* ||A_centered||² = 0.014² + (-0.016)² + 0.024² + 0.004² + (-0.026)²
* ||A_centered||² = 0.000196 + 0.000256 + 0.000576 + 0.000016 + 0.000676 = 0.00172
* ||A_centered|| = √0.00172 ≈ 0.0415
* ||B_centered||² = 0² + 0.01² + (-0.02)² + 0.01² + 0²
* ||B_centered||² = 0 + 0.0001 + 0.0004 + 0.0001 + 0 = 0.0006
* ||B_centered|| = √0.0006 ≈ 0.0245
Step 6: Calculate correlation r = (A_centered · B_centered)/(||A_centered|| × ||B_centered||) r = -0.0006/(0.0415 × 0.0245) ≈ -0.0006/0.001017 ≈ -0.59

AI/ML Problem Solution: Cosine Similarity
Step 1: Set up user preference vectors
* User 1: [4, 2, 1, 3] (Action, Comedy, Drama, Sci-Fi)
* User 2: [3, 3, 2, 4]
Step 2: Calculate inner product User1 · User2 = (4×3) + (2×3) + (1×2) + (3×4) = 12 + 6 + 2 + 12 = 32
Step 3: Calculate norms
* ||User1||² = 4² + 2² + 1² + 3² = 16 + 4 + 1 + 9 = 30
* ||User1|| = √30 ≈ 5.477
* ||User2||² = 3² + 3² + 2² + 4² = 9 + 9 + 4 + 16 = 38
* ||User2|| = √38 ≈ 6.164
Step 4: Calculate cosine similarity cos(θ) = (User1 · User2)/(||User1|| × ||User2||) cos(θ) = 32/(5.477 × 6.164) ≈ 32/33.75 ≈ 0.948

Interpretation:
* Finance: The correlation of -0.59 indicates a moderate negative correlation between assets A and B, which is good for diversification!
* AI/ML: The cosine similarity of 0.948 is very high (close to 1), indicating these users have very similar preferences and would likely enjoy similar recommendations.

In [1]:
"""Finance problem solution"""
import numpy as np
from scipy import stats
import pandas as pd

# Sample data
x = np.array([0.02, -0.01, 0.03, 0.01, -0.02])
y = np.array([0.01, 0.02, -0.01, 0.02, 0.01])

# Pearson correlation coefficient (most common)
pearson_corr = np.corrcoef(x, y)[0, 1]
print(f"Pearson correlation: {pearson_corr:.4f}")

# Using scipy for p-value as well
pearson_corr, p_value = stats.pearsonr(x, y)
print(f"Pearson correlation: {pearson_corr:.4f}, p-value: {p_value:.4f}")

# Spearman correlation (rank-based)
spearman_corr, p_value = stats.spearmanr(x, y)
print(f"Spearman correlation: {spearman_corr:.4f}, p-value: {p_value:.4f}")

# Kendall's tau (another rank-based method)
kendall_corr, p_value = stats.kendalltau(x, y)
print(f"Kendall's tau: {kendall_corr:.4f}, p-value: {p_value:.4f}")

Pearson correlation: -0.5906
Pearson correlation: -0.5906, p-value: 0.2943
Spearman correlation: -0.5270, p-value: 0.3615
Kendall's tau: -0.4472, p-value: 0.2963


In [2]:
"""AI/ML problem solution"""
from scipy.spatial.distance import cosine

# Note: scipy's cosine function returns distance (1 - similarity)
vector1 = [4, 2, 1, 3]
vector2 = [3, 3, 2, 4]

# Calculate cosine distance
cosine_distance = cosine(vector1, vector2)

# Convert to similarity
cosine_sim = 1 - cosine_distance

print(f"Cosine similarity: {cosine_sim:.4f}")
print(f"Cosine distance: {cosine_distance:.4f}")

Cosine similarity: 0.9478
Cosine distance: 0.0522


Day 2: Matrices and Matrix Operations
Key Concepts:
* Matrices: Rectangular arrays of numbers that can represent linear transformations
* Matrix Addition/Subtraction: Element-wise operations
* Matrix Multiplication: Row-by-column multiplication (not element-wise!)
* Transpose: Flipping rows and columns (A^T)
* Inverse: A^(-1) such that AA^(-1) = I (identity matrix)
* Determinant: A scalar value that indicates if a matrix is invertible
Today's Problems:
Finance Problem: A hedge fund uses a 2-factor risk model. The factor loadings matrix F is:
F = [0.8  0.3]  (Stock 1: 0.8 market factor, 0.3 size factor)
    [1.2 -0.1]  (Stock 2: 1.2 market factor, -0.1 size factor)
    [0.6  0.7]  (Stock 3: 0.6 market factor, 0.7 size factor)
The factor returns for this period are: Market = 0.02, Size = 0.01 Portfolio weights are: w = [0.4, 0.4, 0.2]^T
Calculate the portfolio's expected return using matrix multiplication.
AI/ML Problem: In a neural network, you have an input vector x = [2, 3, 1] and a weight matrix:
W = [0.5  0.2  0.3]  (weights from 3 inputs to neuron 1)
    [0.1  0.8 -0.2]  (weights from 3 inputs to neuron 2)
Calculate the pre-activation values (before applying activation function) for both neurons, and find the transpose of W.
Methods to use:
* Matrix multiplication: C = AB where C_ij = Σ(A_ik × B_kj)
* Transpose: (A^T)_ij = A_ji
* For portfolio return: R_portfolio = w^T × F × factor_returns
* For neural network: pre_activation = W × x
Ready to solve these? Type "solve" when you want the step-by-step solutions!


Finance Problem Solution: Portfolio Expected Return
Step 1: Set up the matrices and vectors
F = [0.8  0.3]    factor_returns = [0.02]    w = [0.4]
    [1.2 -0.1]                     [0.01]        [0.4]
    [0.6  0.7]                                   [0.2]
Step 2: Calculate F × factor_returns first
F × factor_returns = [0.8  0.3] × [0.02]
                     [1.2 -0.1]   [0.01]
                     [0.6  0.7]
For each row:
* Row 1: (0.8 × 0.02) + (0.3 × 0.01) = 0.016 + 0.003 = 0.019
* Row 2: (1.2 × 0.02) + (-0.1 × 0.01) = 0.024 - 0.001 = 0.023
* Row 3: (0.6 × 0.02) + (0.7 × 0.01) = 0.012 + 0.007 = 0.019
So: F × factor_returns = [0.019, 0.023, 0.019]^T
Step 3: Calculate portfolio return: w^T × (F × factor_returns)
w^T × [0.019] = [0.4  0.4  0.2] × [0.019]
      [0.023]                     [0.023]
      [0.019]                     [0.019]
Portfolio return = (0.4 × 0.019) + (0.4 × 0.023) + (0.2 × 0.019) = 0.0076 + 0.0092 + 0.0038 = 0.0206 or 2.06%

AI/ML Problem Solution: Neural Network Forward Pass
Step 1: Set up the weight matrix and input vector
W = [0.5  0.2  0.3]    x = [2]
    [0.1  0.8 -0.2]        [3]
                           [1]
Step 2: Calculate pre-activation values: W × x
W × x = [0.5  0.2  0.3] × [2]
        [0.1  0.8 -0.2]   [3]
                          [1]
For each neuron (row):
* Neuron 1: (0.5 × 2) + (0.2 × 3) + (0.3 × 1) = 1.0 + 0.6 + 0.3 = 1.9
* Neuron 2: (0.1 × 2) + (0.8 × 3) + (-0.2 × 1) = 0.2 + 2.4 - 0.2 = 2.4
So: pre_activation = [1.9, 2.4]^T
Step 3: Calculate transpose of W
W^T = [0.5  0.1]  (flip rows and columns)
      [0.2  0.8]
      [0.3 -0.2]

Matrix Dimension Check (Important!):
* Finance: w^T is (1×3), F is (3×2), factor_returns is (2×1) → Final result is (1×1) ✓
* AI/ML: W is (2×3), x is (3×1) → Result is (2×1) ✓
* Transpose: W is (2×3) → W^T is (3×2) ✓
Interpretation:
* Finance: The portfolio's expected return is 2.06%, which is a weighted combination of how each stock responds to the market and size factors.
* AI/ML: The neurons receive inputs of 1.9 and 2.4 respectively before activation. These would then go through an activation function like ReLU or sigmoid.

In [ ]:
"""Finance problem Solution"""
