Day 1: Vectors, Vector Spaces, and Inner Product Spaces
Let me start with the core concepts and then give you today's practical problems.
Key Concepts:
* Vectors: Objects that have magnitude and direction, represented as arrays of numbers
* Vector Spaces: Collections of vectors that can be added together and multiplied by scalars
* Inner Product: A way to multiply vectors that gives a scalar (like dot product)
* Norm: The "length" of a vector, often calculated as √(v·v)
Today's Problems:
Finance Problem: You're analyzing a portfolio with 4 assets. The daily returns over 5 days are represented as vectors:
* Asset A: [0.02, -0.01, 0.03, 0.01, -0.02]
* Asset B: [0.01, 0.02, -0.01, 0.02, 0.01]
Calculate the correlation coefficient between these two assets using vector operations (hint: use inner products and norms).
AI/ML Problem: In a recommendation system, user preferences are represented as vectors. User 1 likes genres with weights [4, 2, 1, 3] for [Action, Comedy, Drama, Sci-Fi], and User 2 has weights [3, 3, 2, 4]. Calculate the cosine similarity between these users to determine how similar their tastes are.
Methods to use:
* Inner product (dot product): a·b = Σ(aᵢbᵢ)
* Vector norm: ||v|| = √(v·v)
* Correlation coefficient: r = (a·b)/(||a|| × ||b||) after centering the data
* Cosine similarity: cos(θ) = (a·b)/(||a|| × ||b||)
Try these problems and when you're ready, type "solve" and I'll walk you through the step-by-step solutions!

Finance Problem Solution: Portfolio Correlation
Step 1: Set up the data
* Asset A returns: [0.02, -0.01, 0.03, 0.01, -0.02]
* Asset B returns: [0.01, 0.02, -0.01, 0.02, 0.01]
Step 2: Calculate means
* Mean of A: μₐ = (0.02 + (-0.01) + 0.03 + 0.01 + (-0.02))/5 = 0.03/5 = 0.006
* Mean of B: μᵦ = (0.01 + 0.02 + (-0.01) + 0.02 + 0.01)/5 = 0.05/5 = 0.01
Step 3: Center the data (subtract means)
* A_centered = [0.02-0.006, -0.01-0.006, 0.03-0.006, 0.01-0.006, -0.02-0.006]
* A_centered = [0.014, -0.016, 0.024, 0.004, -0.026]
* B_centered = [0.01-0.01, 0.02-0.01, -0.01-0.01, 0.02-0.01, 0.01-0.01]
* B_centered = [0, 0.01, -0.02, 0.01, 0]
Step 4: Calculate inner product A_centered · B_centered = (0.014×0) + (-0.016×0.01) + (0.024×-0.02) + (0.004×0.01) + (-0.026×0) = 0 + (-0.00016) + (-0.00048) + 0.00004 + 0 = -0.0006
Step 5: Calculate norms
* ||A_centered||² = 0.014² + (-0.016)² + 0.024² + 0.004² + (-0.026)²
* ||A_centered||² = 0.000196 + 0.000256 + 0.000576 + 0.000016 + 0.000676 = 0.00172
* ||A_centered|| = √0.00172 ≈ 0.0415
* ||B_centered||² = 0² + 0.01² + (-0.02)² + 0.01² + 0²
* ||B_centered||² = 0 + 0.0001 + 0.0004 + 0.0001 + 0 = 0.0006
* ||B_centered|| = √0.0006 ≈ 0.0245
Step 6: Calculate correlation r = (A_centered · B_centered)/(||A_centered|| × ||B_centered||) r = -0.0006/(0.0415 × 0.0245) ≈ -0.0006/0.001017 ≈ -0.59

AI/ML Problem Solution: Cosine Similarity
Step 1: Set up user preference vectors
* User 1: [4, 2, 1, 3] (Action, Comedy, Drama, Sci-Fi)
* User 2: [3, 3, 2, 4]
Step 2: Calculate inner product User1 · User2 = (4×3) + (2×3) + (1×2) + (3×4) = 12 + 6 + 2 + 12 = 32
Step 3: Calculate norms
* ||User1||² = 4² + 2² + 1² + 3² = 16 + 4 + 1 + 9 = 30
* ||User1|| = √30 ≈ 5.477
* ||User2||² = 3² + 3² + 2² + 4² = 9 + 9 + 4 + 16 = 38
* ||User2|| = √38 ≈ 6.164
Step 4: Calculate cosine similarity cos(θ) = (User1 · User2)/(||User1|| × ||User2||) cos(θ) = 32/(5.477 × 6.164) ≈ 32/33.75 ≈ 0.948

Interpretation:
* Finance: The correlation of -0.59 indicates a moderate negative correlation between assets A and B, which is good for diversification!
* AI/ML: The cosine similarity of 0.948 is very high (close to 1), indicating these users have very similar preferences and would likely enjoy similar recommendations.

In [1]:
"""Finance problem solution"""
import numpy as np
from scipy import stats
import pandas as pd

# Sample data
x = np.array([0.02, -0.01, 0.03, 0.01, -0.02])
y = np.array([0.01, 0.02, -0.01, 0.02, 0.01])

# Pearson correlation coefficient (most common)
pearson_corr = np.corrcoef(x, y)[0, 1]
print(f"Pearson correlation: {pearson_corr:.4f}")

# Using scipy for p-value as well
pearson_corr, p_value = stats.pearsonr(x, y)
print(f"Pearson correlation: {pearson_corr:.4f}, p-value: {p_value:.4f}")

# Spearman correlation (rank-based)
spearman_corr, p_value = stats.spearmanr(x, y)
print(f"Spearman correlation: {spearman_corr:.4f}, p-value: {p_value:.4f}")

# Kendall's tau (another rank-based method)
kendall_corr, p_value = stats.kendalltau(x, y)
print(f"Kendall's tau: {kendall_corr:.4f}, p-value: {p_value:.4f}")

Pearson correlation: -0.5906
Pearson correlation: -0.5906, p-value: 0.2943
Spearman correlation: -0.5270, p-value: 0.3615
Kendall's tau: -0.4472, p-value: 0.2963


In [2]:
"""AI/ML problem solution"""
from scipy.spatial.distance import cosine

# Note: scipy's cosine function returns distance (1 - similarity)
vector1 = [4, 2, 1, 3]
vector2 = [3, 3, 2, 4]

# Calculate cosine distance
cosine_distance = cosine(vector1, vector2)

# Convert to similarity
cosine_sim = 1 - cosine_distance

print(f"Cosine similarity: {cosine_sim:.4f}")
print(f"Cosine distance: {cosine_distance:.4f}")

Cosine similarity: 0.9478
Cosine distance: 0.0522


Day 2: Matrices and Matrix Operations
Key Concepts:
* Matrices: Rectangular arrays of numbers that can represent linear transformations
* Matrix Addition/Subtraction: Element-wise operations
* Matrix Multiplication: Row-by-column multiplication (not element-wise!)
* Transpose: Flipping rows and columns (A^T)
* Inverse: A^(-1) such that AA^(-1) = I (identity matrix)
* Determinant: A scalar value that indicates if a matrix is invertible
Today's Problems:
Finance Problem: A hedge fund uses a 2-factor risk model. The factor loadings matrix F is:
F = [0.8  0.3]  (Stock 1: 0.8 market factor, 0.3 size factor)
    [1.2 -0.1]  (Stock 2: 1.2 market factor, -0.1 size factor)
    [0.6  0.7]  (Stock 3: 0.6 market factor, 0.7 size factor)
The factor returns for this period are: Market = 0.02, Size = 0.01 Portfolio weights are: w = [0.4, 0.4, 0.2]^T
Calculate the portfolio's expected return using matrix multiplication.
AI/ML Problem: In a neural network, you have an input vector x = [2, 3, 1] and a weight matrix:
W = [0.5  0.2  0.3]  (weights from 3 inputs to neuron 1)
    [0.1  0.8 -0.2]  (weights from 3 inputs to neuron 2)
Calculate the pre-activation values (before applying activation function) for both neurons, and find the transpose of W.
Methods to use:
* Matrix multiplication: C = AB where C_ij = Σ(A_ik × B_kj)
* Transpose: (A^T)_ij = A_ji
* For portfolio return: R_portfolio = w^T × F × factor_returns
* For neural network: pre_activation = W × x
Ready to solve these? Type "solve" when you want the step-by-step solutions!


Finance Problem Solution: Portfolio Expected Return
Step 1: Set up the matrices and vectors
F = [0.8  0.3]    factor_returns = [0.02]    w = [0.4]
    [1.2 -0.1]                     [0.01]        [0.4]
    [0.6  0.7]                                   [0.2]
Step 2: Calculate F × factor_returns first
F × factor_returns = [0.8  0.3] × [0.02]
                     [1.2 -0.1]   [0.01]
                     [0.6  0.7]
For each row:
* Row 1: (0.8 × 0.02) + (0.3 × 0.01) = 0.016 + 0.003 = 0.019
* Row 2: (1.2 × 0.02) + (-0.1 × 0.01) = 0.024 - 0.001 = 0.023
* Row 3: (0.6 × 0.02) + (0.7 × 0.01) = 0.012 + 0.007 = 0.019
So: F × factor_returns = [0.019, 0.023, 0.019]^T
Step 3: Calculate portfolio return: w^T × (F × factor_returns)
w^T × [0.019] = [0.4  0.4  0.2] × [0.019]
      [0.023]                     [0.023]
      [0.019]                     [0.019]
Portfolio return = (0.4 × 0.019) + (0.4 × 0.023) + (0.2 × 0.019) = 0.0076 + 0.0092 + 0.0038 = 0.0206 or 2.06%

AI/ML Problem Solution: Neural Network Forward Pass
Step 1: Set up the weight matrix and input vector
W = [0.5  0.2  0.3]    x = [2]
    [0.1  0.8 -0.2]        [3]
                           [1]
Step 2: Calculate pre-activation values: W × x
W × x = [0.5  0.2  0.3] × [2]
        [0.1  0.8 -0.2]   [3]
                          [1]
For each neuron (row):
* Neuron 1: (0.5 × 2) + (0.2 × 3) + (0.3 × 1) = 1.0 + 0.6 + 0.3 = 1.9
* Neuron 2: (0.1 × 2) + (0.8 × 3) + (-0.2 × 1) = 0.2 + 2.4 - 0.2 = 2.4
So: pre_activation = [1.9, 2.4]^T
Step 3: Calculate transpose of W
W^T = [0.5  0.1]  (flip rows and columns)
      [0.2  0.8]
      [0.3 -0.2]

Matrix Dimension Check (Important!):
* Finance: w^T is (1×3), F is (3×2), factor_returns is (2×1) → Final result is (1×1) ✓
* AI/ML: W is (2×3), x is (3×1) → Result is (2×1) ✓
* Transpose: W is (2×3) → W^T is (3×2) ✓
Interpretation:
* Finance: The portfolio's expected return is 2.06%, which is a weighted combination of how each stock responds to the market and size factors.
* AI/ML: The neurons receive inputs of 1.9 and 2.4 respectively before activation. These would then go through an activation function like ReLU or sigmoid.

In [1]:
"""Finance Problem Solution"""
F = np.array([[0.8, 0.3],
              [1.2, -0.1],
              [0.6, 0.7]])

R_f = np.array([[0.02],
                [0.01]])

w = np.array([[0.4],
              [0.4],
              [0.2]])

# Matrix multiplication: wᵀ × F × R_f
portfolio_return = w.T @ F @ R_f

print("PORTFOLIO EXPECTED RETURN CALCULATION")
print("=====================================")
print("Factor loadings matrix (F):")
print(F)
print(f"\nFactor returns (R_f): Market = {R_f[0][0]}, Size = {R_f[1][0]}")
print(f"Portfolio weights (w): Stock 1 = {w[0][0]}, Stock 2 = {w[1][0]}, Stock 3 = {w[2][0]}")

# Show step-by-step calculation
print("\nSTEP-BY-STEP CALCULATION:")
print("1. Calculate F × R_f (individual factor contributions):")
factor_contributions = F @ R_f
print(factor_contributions)

print("\n2. Calculate wᵀ × (F × R_f) (portfolio return):")
print(f"Portfolio return = {portfolio_return[0][0]:.4f}")

print(f"\nFINAL ANSWER: {portfolio_return[0][0]:.4f} ({portfolio_return[0][0]*100:.2f}%)")

PORTFOLIO EXPECTED RETURN CALCULATION
Factor loadings matrix (F):
[[ 0.8  0.3]
 [ 1.2 -0.1]
 [ 0.6  0.7]]

Factor returns (R_f): Market = 0.02, Size = 0.01
Portfolio weights (w): Stock 1 = 0.4, Stock 2 = 0.4, Stock 3 = 0.2

STEP-BY-STEP CALCULATION:
1. Calculate F × R_f (individual factor contributions):
[[0.019]
 [0.023]
 [0.019]]

2. Calculate wᵀ × (F × R_f) (portfolio return):
Portfolio return = 0.0206

FINAL ANSWER: 0.0206 (2.06%)


In [4]:
"""AI/ML Problem Solution"""
x = np.array([2, 3, 1])
W = np.array([[0.5, 0.2, 0.3],
              [0.1, 0.8, -0.2]])

# 1. Calculate pre-activation
z = W @ x

# 2. Calculate transpose
W_transpose = W.T

print("NEURAL NETWORK CALCULATION")
print("==========================")
print("Input vector x:", x)
print("\nWeight matrix W:")
print(W)

print(f"\nPre-activation calculation:")
print("Neuron 1: (0.5×2) + (0.2×3) + (0.3×1) = 1.0 + 0.6 + 0.3 = 1.9")
print("Neuron 2: (0.1×2) + (0.8×3) + (-0.2×1) = 0.2 + 2.4 - 0.2 = 2.4")

print(f"\nPre-activation values z: {z}")
print(f"→ Neuron 1: {z[0]:.1f}")
print(f"→ Neuron 2: {z[1]:.1f}")

print("\nTranspose of W:")
print(W_transpose)

NEURAL NETWORK CALCULATION
Input vector x: [2 3 1]

Weight matrix W:
[[ 0.5  0.2  0.3]
 [ 0.1  0.8 -0.2]]

Pre-activation calculation:
Neuron 1: (0.5×2) + (0.2×3) + (0.3×1) = 1.0 + 0.6 + 0.3 = 1.9
Neuron 2: (0.1×2) + (0.8×3) + (-0.2×1) = 0.2 + 2.4 - 0.2 = 2.4

Pre-activation values z: [1.9 2.4]
→ Neuron 1: 1.9
→ Neuron 2: 2.4

Transpose of W:
[[ 0.5  0.1]
 [ 0.2  0.8]
 [ 0.3 -0.2]]


Day 3: Eigenvalues and Eigenvectors
Key Concepts:
* Eigenvector: A vector v that doesn't change direction when transformed by matrix A (only scales)
* Eigenvalue: The scaling factor λ such that Av = λv
* Characteristic Equation: det(A - λI) = 0 to find eigenvalues
* Eigendecomposition: A = PΛP^(-1) where P contains eigenvectors, Λ contains eigenvalues
* Applications: Principal directions, stability analysis, dimensionality reduction
Today's Problems:
Finance Problem: A risk manager is analyzing a 2-asset portfolio covariance matrix:
C = [0.04  0.02]  (Asset 1 variance: 0.04, covariance: 0.02)
    [0.02  0.09]  (Asset 2 variance: 0.09, covariance: 0.02)
Find the eigenvalues and eigenvectors of this covariance matrix. The eigenvalues represent the variance along the principal risk directions, and eigenvectors show the portfolio compositions for these principal directions.
AI/ML Problem: In a simple neural network, the weight matrix between two layers is:
W = [3  1]
    [0  2]
Find the eigenvalues and eigenvectors. These help understand how the network amplifies or dampens information along different directions during forward/backward propagation.
Methods to use:
* For 2×2 matrix A = [a b; c d]:
    * Characteristic equation: λ² - (a+d)λ + (ad-bc) = 0
    * Trace = a + d, Determinant = ad - bc
    * Use quadratic formula: λ = [(a+d) ± √((a+d)² - 4(ad-bc))] / 2
* For eigenvectors: Solve (A - λI)v = 0 for each eigenvalue λ
Ready to dive into the calculations? Type "solve" for step-by-step solutions!


Finance Problem Solution: Portfolio Covariance Matrix
Step 1: Set up the covariance matrix
C = [0.04  0.02]
    [0.02  0.09]
Step 2: Find the characteristic equation det(C - λI) = 0
C - λI = [0.04-λ   0.02  ]
         [0.02     0.09-λ]
Determinant = (0.04-λ)(0.09-λ) - (0.02)(0.02) = 0.0036 - 0.04λ - 0.09λ + λ² - 0.0004 = λ² - 0.13λ + 0.0032 = 0
Step 3: Solve for eigenvalues using quadratic formula λ = [0.13 ± √(0.13² - 4(1)(0.0032))] / 2 λ = [0.13 ± √(0.0169 - 0.0128)] / 2 λ = [0.13 ± √0.0041] / 2 λ = [0.13 ± 0.064] / 2
Eigenvalues:
* λ₁ = (0.13 + 0.064)/2 = 0.097
* λ₂ = (0.13 - 0.064)/2 = 0.033
Step 4: Find eigenvectors
For λ₁ = 0.097:
(C - 0.097I)v₁ = 0
[-0.057  0.02 ] [v₁₁] = [0]
[0.02   -0.007] [v₁₂]   [0]
From first row: -0.057v₁₁ + 0.02v₁₂ = 0 So: v₁₂ = (0.057/0.02)v₁₁ = 2.85v₁₁
Eigenvector 1: v₁ = [1, 2.85]ᵀ (normalized: [0.33, 0.94]ᵀ)
For λ₂ = 0.033:
(C - 0.033I)v₂ = 0
[0.007  0.02] [v₂₁] = [0]
[0.02   0.057] [v₂₂]   [0]
From first row: 0.007v₂₁ + 0.02v₂₂ = 0 So: v₂₁ = -(0.02/0.007)v₂₂ = -2.86v₂₂
Eigenvector 2: v₂ = [-2.86, 1]ᵀ (normalized: [-0.94, 0.33]ᵀ)

AI/ML Problem Solution: Neural Network Weight Matrix
Step 1: Set up the weight matrix
W = [3  1]
    [0  2]
Step 2: Find characteristic equation det(W - λI) = 0
W - λI = [3-λ  1  ]
         [0    2-λ]
Since this is upper triangular, determinant = (3-λ)(2-λ) - (1)(0) = (3-λ)(2-λ)
Step 3: Solve for eigenvalues (3-λ)(2-λ) = 0
Eigenvalues:
* λ₁ = 3
* λ₂ = 2
Step 4: Find eigenvectors
For λ₁ = 3:
(W - 3I)v₁ = 0
[0  1] [v₁₁] = [0]
[0 -1] [v₁₂]   [0]
From first row: v₁₂ = 0 Eigenvector 1: v₁ = [1, 0]ᵀ
For λ₂ = 2:
(W - 2I)v₂ = 0
[1  1] [v₂₁] = [0]
[0  0] [v₂₂]   [0]
From first row: v₂₁ + v₂₂ = 0, so v₂₂ = -v₂₁ Eigenvector 2: v₂ = [1, -1]ᵀ

Interpretation:
Finance Problem:
* λ₁ = 0.097: Maximum portfolio risk direction with 97% of variance
* λ₂ = 0.033: Minimum risk direction with 33% of variance
* Eigenvector 1 [0.33, 0.94]: Portfolio heavily weighted toward Asset 2
* Eigenvector 2 [-0.94, 0.33]: Short Asset 1, long Asset 2 - this is the minimum variance portfolio direction!
AI/ML Problem:
* λ₁ = 3: Information is amplified 3× along direction [1,0] (first input dimension)
* λ₂ = 2: Information is amplified 2× along direction [1,-1] (difference between inputs)
* Both eigenvalues > 1 suggest this layer amplifies signals, which could lead to exploding gradients if not controlled

In [6]:
"""Finance Problem Solution"""
import numpy as np
# Given covariance matrix
C = np.array([[0.04, 0.02],
              [0.02, 0.09]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(C)

print("PORTFOLIO RISK ANALYSIS")
print("=======================")
print("Covariance Matrix C:")
print(C)

print(f"\nEigenvalues: {eigenvalues}")
print("Principal Risk Directions (variance along each direction):")
for i, λ in enumerate(eigenvalues):
    print(f"Direction {i+1}: Variance = {λ:.4f}")

print("\nEigenvectors (portfolio compositions):")
for i in range(eigenvectors.shape[1]):
    v = eigenvectors[:, i]
    print(f"Principal Direction {i+1}: {v} (sum: {v.sum():.2f})")

# Normalize eigenvectors to sum to 1 (portfolio weights)
print("\nNormalized Portfolio Weights (sum to 1):")
for i in range(eigenvectors.shape[1]):
    v = eigenvectors[:, i]
    normalized_v = v / v.sum()
    print(f"Direction {i+1}: {normalized_v} → Asset 1: {normalized_v[0]:.1%}, Asset 2: {normalized_v[1]:.1%}")

PORTFOLIO RISK ANALYSIS
Covariance Matrix C:
[[0.04 0.02]
 [0.02 0.09]]

Eigenvalues: [0.03298438 0.09701562]
Principal Risk Directions (variance along each direction):
Direction 1: Variance = 0.0330
Direction 2: Variance = 0.0970

Eigenvectors (portfolio compositions):
Principal Direction 1: [-0.94362832  0.33100694] (sum: -0.61)
Principal Direction 2: [-0.33100694 -0.94362832] (sum: -1.27)

Normalized Portfolio Weights (sum to 1):
Direction 1: [ 1.54031242 -0.54031242] → Asset 1: 154.0%, Asset 2: -54.0%
Direction 2: [0.25968758 0.74031242] → Asset 1: 26.0%, Asset 2: 74.0%


In [7]:
"""AI/ML Problem Solution"""
import numpy as np

# Given weight matrix
W = np.array([[3, 1],
              [0, 2]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(W)

print("NEURAL NETWORK EIGENANALYSIS")
print("============================")
print("Weight Matrix W:")
print(W)

print(f"\nEigenvalues: {eigenvalues}")
print("Information Amplification Factors:")
for i, λ in enumerate(eigenvalues):
    amplification = abs(λ)
    effect = "amplifies" if amplification > 1 else "dampens" if amplification < 1 else "preserves"
    print(f"Direction {i+1}: Factor = {λ:.2f} ({effect} information)")

print("\nEigenvectors (principal directions):")
for i in range(eigenvectors.shape[1]):
    v = eigenvectors[:, i]
    print(f"Principal Direction {i+1}: {v}")

# Analyze the transformation
print("\nTRANSFORMATION ANALYSIS:")
print("During forward propagation, inputs along eigenvector directions")
print("get scaled by the corresponding eigenvalues:")

NEURAL NETWORK EIGENANALYSIS
Weight Matrix W:
[[3 1]
 [0 2]]

Eigenvalues: [3. 2.]
Information Amplification Factors:
Direction 1: Factor = 3.00 (amplifies information)
Direction 2: Factor = 2.00 (amplifies information)

Eigenvectors (principal directions):
Principal Direction 1: [1. 0.]
Principal Direction 2: [-0.70710678  0.70710678]

TRANSFORMATION ANALYSIS:
During forward propagation, inputs along eigenvector directions
get scaled by the corresponding eigenvalues:


Day 4: Diagonalization and SVD (Singular Value Decomposition)
Key Concepts:
* Diagonalization: A = PDP^(-1) where D is diagonal (eigenvalues), P contains eigenvectors
* SVD: A = UΣV^T where U,V are orthogonal matrices, Σ contains singular values
* Singular Values: Square roots of eigenvalues of A^T A (always non-negative)
* Rank: Number of non-zero singular values
* Applications: Data compression, noise reduction, dimensionality reduction
Today's Problems:
Finance Problem: A quantitative analyst wants to compress a returns correlation matrix for computational efficiency. Given the 3×3 correlation matrix:
R = [1.0   0.8   0.6]
    [0.8   1.0   0.5]
    [0.6   0.5   1.0]
Perform SVD decomposition R = UΣV^T. The largest singular values capture the most important correlation patterns. How much variance is captured by the first two components?
AI/ML Problem: In collaborative filtering, you have a user-item rating matrix (simplified 2×3):
A = [4  0  2]  (User 1 ratings: Movie 1=4, Movie 2=0, Movie 3=2)
    [0  3  1]  (User 2 ratings: Movie 1=0, Movie 2=3, Movie 3=1)
Find the SVD of this matrix. The decomposition reveals latent factors (like genres) that explain user preferences and can help predict missing ratings.
Methods to use:
* For small matrices, use the relationship: A^T A and AA^T share eigenvalues
* Singular values: σᵢ = √(eigenvalues of A^T A)
* Variance explained: (σᵢ²)/(sum of all σⱼ²)
* For 2×2 case: Can use direct formulas or numerical methods
* Check: A = UΣV^T should reconstruct the original matrix
Ready to decompose these matrices? Type "solve" for the step-by-step SVD calculations!




Excellent! Let me walk you through both SVD problems step by step.
Finance Problem Solution: Correlation Matrix SVD
Step 1: Set up the correlation matrix
R = [1.0  0.8  0.6]
    [0.8  1.0  0.5]
    [0.6  0.5  1.0]
Step 2: Calculate R^T R (since R is symmetric, R^T R = R²)
R² = [1.0  0.8  0.6] × [1.0  0.8  0.6]
     [0.8  1.0  0.5]   [0.8  1.0  0.5]
     [0.6  0.5  1.0]   [0.6  0.5  1.0]
Computing each element:
R² = [1.0+0.64+0.36   0.8+0.8+0.3    0.6+0.4+0.6 ]   [2.0   1.9   1.6]
     [0.8+0.8+0.3     0.64+1.0+0.25  0.48+0.5+0.5]  = [1.9   1.89  1.48]
     [0.6+0.4+0.6     0.48+0.5+0.5   0.36+0.25+1.0]   [1.6   1.48  1.61]
Step 3: Find eigenvalues of R² (characteristic equation) For a 3×3 matrix, this involves solving a cubic equation. Using numerical methods:
Eigenvalues of R²:
* λ₁ ≈ 4.41
* λ₂ ≈ 1.09
* λ₃ ≈ 0.00 (very small, essentially 0)
Step 4: Calculate singular values
* σ₁ = √4.41 ≈ 2.10
* σ₂ = √1.09 ≈ 1.04
* σ₃ = √0.00 ≈ 0.00
Step 5: Calculate variance explained Total variance = σ₁² + σ₂² + σ₃² = 4.41 + 1.09 + 0.00 = 5.50
* First component: 4.41/5.50 = 80.2%
* Second component: 1.09/5.50 = 19.8%
* First two components capture: 80.2% + 19.8% = 100%

AI/ML Problem Solution: User-Item Matrix SVD
Step 1: Set up the rating matrix
A = [4  0  2]
    [0  3  1]
Step 2: Calculate A^T A
A^T = [4  0]    A^T A = [4  0] × [4  0  2] = [16   0   8]
      [0  3]            [0  3]   [0  3  1]   [0    9   3]
      [2  1]            [2  1]               [8    3   5]
Step 3: Find eigenvalues of A^T A
A^T A - λI = [16-λ   0    8  ]
             [0      9-λ  3  ]
             [8      3    5-λ]
This gives us the characteristic equation. Using numerical methods:
Eigenvalues of A^T A:
* λ₁ ≈ 21.55
* λ₂ ≈ 8.45
* λ₃ ≈ 0.00
Step 4: Calculate singular values
* σ₁ = √21.55 ≈ 4.64
* σ₂ = √8.45 ≈ 2.91
* σ₃ = √0.00 ≈ 0.00
Step 5: Calculate AA^T for left singular vectors
AA^T = [4  0  2] × [4  0] = [20  2]
       [0  3  1]   [0  3]   [2   10]
                   [2  1]
Eigenvalues of AA^T: 21.55, 8.45 (same non-zero values as A^T A)
Step 6: Rank and interpretation The matrix has rank 2 (two non-zero singular values), meaning there are 2 latent factors.

Interpretation:
Finance Problem:
* The correlation matrix can be perfectly represented by 2 components (100% variance captured)
* First component (σ₁=2.10): Captures the main correlation structure (80.2% of relationships)
* Second component (σ₂=1.04): Captures remaining correlation patterns (19.8%)
* This suggests the 3 assets can be explained by 2 underlying risk factors
AI/ML Problem:
* Rank 2 matrix reveals 2 latent factors (e.g., "Action" and "Romance" genres)
* σ₁=4.64: Dominant preference pattern
* σ₂=2.91: Secondary preference pattern
* Missing ratings can be predicted using: A ≈ σ₁u₁v₁^T + σ₂u₂v₂^T
Practical Applications:
* Finance: Risk factor models, portfolio optimization
* ML: Collaborative filtering, dimensionality reduction, data compression

In [ ]:
"""Finance Problem Solution"""
